name: launcher_switch
description: "This is a flutter package that will enable you switch between different laucher icons in your app."
version: 0.0.1
homepage: https://github.com/rans-rans/launcher_switch.git

environment:
  sdk: '>=3.2.5 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.rans_innovations.launcher_switch
        pluginClass: LauncherSwitchPlugin
